Length Target Train Loader: 11157
Length Target Validation Loader: 63
Length Source Train Loader: 11157
No checkpoint is used. Training from scratch!
[{'silog_depth': {'weight': 0.85}, 'bce': {'r': 0.3, 'ignore_index': 250}, 'snr': 'None'}]
[{'silog_depth': 1, 'bce': 0.001, 'snr': 0.01}]
Training supervised on source dataset using dense depth!
Training supervised on source dataset using semantic annotations!
Source ground truth scale is used for computing depth errors while training.
Source ground truth scale is used for computing depth errors while validating.
Training unsupervised on target dataset using self supervised depth!
Training started...
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 149, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 50, in send
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 183, in send_handle
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 543, in fromfd
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
!m  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
}  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
    df = multiprocessing.reduction.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
Process Process-22:
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 260, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 159, in recvfds
    raise EOFError
EOFError
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
    new_fd = os.dup(fd)
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
    new_fd = os.dup(fd)
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
    with self._listener.accept() as conn:
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 463, in accept
    c = self._listener.accept()
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 609, in accept
    s, self._last_accepted = self._socket.accept()
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/socket.py", line 292, in accept
    fd, addr = self._accept()
OSError: [Errno 24] Too many open files
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fc6683c1ee0>
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1301, in _shutdown_workers
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
    with self._listener.accept() as conn:
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 465, in accept
    deliver_challenge(c, self._authkey)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 740, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/resource_sharer.py", line 142, in _serve
    with self._listener.accept() as conn:
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 465, in accept
    deliver_challenge(c, self._authkey)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 738, in deliver_challenge
    connection.send_bytes(CHALLENGE + message)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/bauschb/miniconda3/envs/Masterthesis/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 4021421) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.